// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Statistics.Infrastructure;

#nullable disable

namespace Statistics.SqlServerMigrations.Migrations
{
    [DbContext(typeof(StatisticsDbContext))]
    [Migration("20250331103057_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Statistics.Domain.TotalStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalOrdersCreated")
                        .HasColumnType("int");

                    b.Property<int>("TotalProductsCreated")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TotalStatistics");
                });
#pragma warning restore 612, 618
        }
    }
}
