// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderManagement.Infrastructure;

#nullable disable

<<<<<<<< HEAD:SimplyLifestyleApi/OrderManagement/OrderManagement.SqlServerMigrations/Migrations/20250125183834_InitialMigration.Designer.cs
namespace Orders.Infrastructure.Migrations
{
    [DbContext(typeof(OrderManagementDbContext))]
    [Migration("20250125183834_InitialMigration")]
========
namespace OrderManagement.SqlServerMigrations.Migrations
{
    [DbContext(typeof(OrderManagementDbContext))]
    [Migration("20250331104924_InitialMigration")]
>>>>>>>> feature/api:SimplyLifestyleApi/OrderManagement/OrderManagement.SqlServerMigrations/Migrations/20250331104924_InitialMigration.Designer.cs
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
<<<<<<<< HEAD:SimplyLifestyleApi/OrderManagement/OrderManagement.SqlServerMigrations/Migrations/20250125183834_InitialMigration.Designer.cs
                .HasAnnotation("ProductVersion", "9.0.0")
========
                .HasAnnotation("ProductVersion", "9.0.3")
>>>>>>>> feature/api:SimplyLifestyleApi/OrderManagement/OrderManagement.SqlServerMigrations/Migrations/20250331104924_InitialMigration.Designer.cs
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderManagement.Domain.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DeliveryDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("OrderDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("OrderManagement.Domain.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("OrderManagement.Domain.Order", b =>
                {
                    b.OwnsOne("OrderManagement.Domain.OrderStatus", "Status", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Value")
                                .HasColumnType("int");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("OrderManagement.Domain.OrderItem", b =>
                {
                    b.HasOne("OrderManagement.Domain.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderManagement.Domain.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
